agents/q_learning/q_agent.py
docs/q-learning.md

Update many parameters and fix errors, including mlflow.
Manually

Q-learning-improve

---

agents/agent_utils.py
agents/q_learning/check_q_table.py
agents/q_learning/q_agent.py
docs/q-learning.md

We add the first version of the conceptual agent. For now only translating Networks (and not even that fully implemented). It can win very nicely.
Improved the check-q-table and add early stop for the agent.
Manually running and winning

Qlearning-improve

---

agents/gnn_dqn/gnn_dqn_agent.py
agents/gnn_dqn/schema.pbtxt
agents/graph_agent_utils.py

Simplified graph representation of the state. DQN agent that uses the new representation

Ondra new graph representation

---

agents/interactive_tui/assistant.py
agents/interactive_tui/interactive_tui.py
agents/llm_utils.py

TUI agent: Add local LLM support through ollama and fix the error with exploit service parsing.
Manually and with various LLms

TUI agent: Add local LLM support through ollama

---

agents/interactive_tui/assistant.py
agents/interactive_tui/interactive_tui.py
agents/llm_utils.py

Improve the look and feel and some minor improvements on how services and data are presented.
Manual testing

Prepare TUI for BSides

---

agents/interactive_tui/interactive_tui.py
agents/interactive_tui/layout.tcss

Added buttons and prettified output.
By me

Add some more buttons

---

agents/interactive_tui/interactive_tui.py

Remove the random move and just print a message.
Manually.

Remove random move

---

agents/interactive_tui/assistant.py

Fix the incorrect prompt.
manually

Fix prompt

---

agents/interactive_tui/assistant.py
agents/interactive_tui/interactive_tui.py
agents/llm_qa/llm_agent_qa.py

Improve the TUI by calling the LLMs asynchronously.
Manually.

Mari tui bsides

---

agents/interactive_tui/interactive_tui.py

Add logging for environment actions.
Fix typo in the invalid action printing.
Manually.

Add logging for environment actions

---

agents/interactive_tui/interactive_tui.py

Fix typo in red color

---

agents/interactive_tui/interactive_tui.py

Fix invalid action

---

agents/interactive_tui/interactive_tui.py

Add the names of ollama modes so we can use them locally
manually

interactive_tui. Add ollama names to use

---

agents/agent_utils.py
agents/q_learning/q_agent.py
docs/q-learning.md

Improve q learning agent
manually

Qlearning improve

---

agents/interactive_tui/interactive_tui.py

Fixes #62 
- Added checks that prevent TUI from crashing if an invalid IP or network is provided.
- Added validation for IPv6 address.
Manually.

Fix for issue #62

---

agents/benign_random/benign_random_agent.py
docs/bening_random.md

Check and small fixes in bening random
Manually

Sebas-check-bening-agent

---

agents/agent_utils.py
agents/base_agent.py
agents/benign_random/benign_random_agent.py
agents/q_learning/q_agent.py

PR to test if the test pass for the new agents
By hand
- [] I have made corresponding changes to the documentation

Ondra-move-functionality-to-coordinator

---

agents/interactive_tui/interactive_tui.py

In some cases an error was shown in the log even though the action was parsed properly
Manual tests

Fix some bugs in the action generation

---

agents/attackers/markov_chain_agent/genetic/config.json
agents/attackers/markov_chain_agent/genetic/genetic_agent.py
agents/attackers/markov_chain_agent/markov_chain_agent.py
agents/attackers/markov_chain_agent/transition_probabilities.json
agents/attackers/markov_chain_agent/utils/filter_winning_solutions.py
agents/attackers/markov_chain_agent/utils/solutions_analyzer.py
agents/attackers/markov_chain_agent/utils/solutions_to_matrix.py
docs/markov_chain.md

Add Markov Chain Agent

---

agents/attackers/llm_qa/llm_action_planner.py
agents/attackers/llm_qa/llm_agent_qa.py
agents/attackers/llm_qa/prompts.yaml

A major refactoring of the llm_qa agent to adapt to the new action structure containing the `src_host`. Most of the code is adapted from the `assistant.py` code used in the `interactive_tui` agent.  The refactoring basically separates llm interaction from the agent behavior. in addition prompts are saved in a YAML file.
The current version of the agent has  won  in the` scenario1` using gpt-4o-mini.  
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code

major refactoring in the llm_qa agent

---

agents/attackers/random/random_agent.py
agents/base_agent.py

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Check eof in communication

---

agents/attackers/markov_chain_agent/markov_chain_agent.py
agents/attackers/markov_chain_agent/utils/solutions_analyzer.py

Updated MC to work with defender and latest changes. Integrated Mlflow
Manual testing

Updated MC to work with defender and latest changes

---

README.md

Some spelling, grammar, and formatting changes

Update README.md:  minor spelling, grammar, formatting

---

agents/attackers/llm_qa/README.md
agents/attackers/llm_qa/llm_agent_qa.py

1. Add support for local models
2. Add support for disabling mlflow
3. Minimal documentation in README.md
- [X ] New feature (non-breaking change which adds functionality)
I run the agents several times with and without mlflow

Harpo local llm support

---

README.md
agents/agent_utils.py
agents/attackers/concepts_q_learning/conceptual_q_agent.py
agents/attackers/interactive_tui/assistant.py
agents/attackers/interactive_tui/interactive_tui.py
agents/attackers/llm_qa/llm_action_planner.py
agents/attackers/llm_qa/llm_agent_qa.py
agents/attackers/q_learning/q_agent.py
agents/attackers/random/random_agent.py
agents/attackers/sarsa/sarsa_agent.py
agents/attackers/scripted_attacker/scripted_attacker.py
agents/base_agent.py
agents/benign/random/benign_random_agent.py
agents/defenders/probabilistic/probabilistic_agent.py
agents/defenders/random/random_agent.py
agents/graph_agent_utils.py
agents/llm_utils.py
pyproject.toml

Add optional dependencies for agents. Fixed imports and installation with pyproject

Optional depedencies

---

agents/attackers/interactive_tui/README.md
agents/attackers/interactive_tui/interactive_tui.py
agents/attackers/sarsa/README.md
pyproject.toml

Added option to run the tui agent in the web interface instead of the CLI
Manual testing in fresh vevn

Add web tui

---

agents/attackers/interactive_tui/assistant.py
agents/attackers/llm_qa/llm_action_planner.py
agents/attackers/llm_qa/llm_agent_qa.py
agents/attackers/scripted_attacker/scripted_attacker.py

Minor cleanup of the code and imports based on the issues found by ruff
Code tested manually

Ruff cleanup

---

agents/attackers/initialized_q_learning/initialized_q_agent.py
agents/attackers/initialized_q_learning/transition_probabilities.json
agents/attackers/markov_chain_agent/genetic/genetic_agent.py
agents/attackers/markov_chain_agent/markov_chain_agent.py

Added Initialized Q Agent and fixed bugs on Q Agent
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Added Initialized Q Agent and fixed bugs on Q Agent

---

agents/attackers/initialized_q_learning/initialized_q_agent.py

Bug Fix initialized q learning

---

agents/attackers/initialized_q_learning/initialized_q_agent.py

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

replace init-q-learning from aidojo-stable branch

---

agents/attackers/initialized_q_learning/initialized_q_agent.py

Support for wandb logging until new baseagent implementation

add support for wandb into init-q-learning agent

---

agents/base_agent.py

Adaptation of the base agent to support additional parameters of ActionType. ResetGame
added new parameter, default value to False keeps the agent functionality intact
manual testing

Ondra add topology randomization request
